const $=s=>document.querySelector(s);let configValues={};
async function api(path,options={}){const r=await fetch(path,{headers:{"Content-Type":"application/json",...(options.headers||{})},...options});if(r.status===401){location.href="/login";throw new Error("Authentication required")}const data=await r.json();if(!r.ok)throw new Error(typeof data.detail==="string"?data.detail:JSON.stringify(data.detail));return data}
const fmt=(v,d=2)=>v===null||v===undefined?"—":Number(v).toLocaleString(undefined,{maximumFractionDigits:d});
const money=v=>v===null||v===undefined?"—":`$${fmt(v,4)}`;const pct=v=>v===null||v===undefined?"—":`${fmt(Number(v)*100,3)}%`;
function metric(label,value,cls=""){return `<div class="metric"><span>${label}</span><strong class="${cls}">${value}</strong></div>`}
function stateClass(v){return ["healthy","ok","connected","true"].includes(String(v).toLowerCase())?"ok":["blocked","false","stopped","unhealthy"].includes(String(v).toLowerCase())?"blocked-text":"warning-text"}
function table(rows,cols){if(!rows?.length)return `<p class=muted>No records</p>`;return `<table><thead><tr>${cols.map(c=>`<th>${c[0]}</th>`).join("")}</tr></thead><tbody>${rows.map(row=>`<tr>${cols.map(c=>`<td>${c[1](row)}</td>`).join("")}</tr>`).join("")}</tbody></table>`}
async function loadStatus(){const s=await api("/api/status");$("#mode").textContent=s.mode.replace("_"," ").toUpperCase();$("#health").textContent=s.status.toUpperCase();$("#health").className=`pill ${s.status}`;$("#attention").classList.toggle("hidden",!s.exposure_requires_attention);$("#systemMetrics").innerHTML=metric("Bot",s.running?"RUNNING":"STOPPED",stateClass(s.running))+metric("WebSocket",s.websocket?"HEALTHY":"STOPPED",stateClass(s.websocket))+metric("CLOB",s.clob_status.toUpperCase(),stateClass(s.clob_status))+metric("Scanner",s.scanner?"HEALTHY":"STOPPED",stateClass(s.scanner))+metric("Markets",fmt(s.markets,0))+metric("Tokens",fmt(s.tokens,0))+metric("Liquid books",fmt(s.books_with_liquidity,0))+metric("Book updates",fmt(s.book_updates,0))+metric("Uptime",`${fmt(s.uptime,0)}s`)+metric("Geoblock",s.geoblock.trading_allowed?"ALLOWED":"BLOCKED",stateClass(s.geoblock.trading_allowed))+metric("Country",s.geoblock.country||"—");const x=s.strategy||{};$("#strategyMetrics").innerHTML=metric("Markets analyzed",fmt(x.markets_analyzed,0))+metric("Raw buy",fmt(x.buy_opportunities_raw,0))+metric("Raw sell",fmt(x.sell_opportunities_raw,0))+metric("Detected",fmt(x.opportunities_found,0))+metric("Rejected stale",fmt(x.rejected_stale,0))+metric("Rejected edge",fmt(x.rejected_edge,0))+metric("Best buy edge",pct(x.best_buy_edge_seen))+metric("Best sell edge",pct(x.best_sell_edge_seen))+metric("Best net edge",pct(x.best_net_edge_seen))+metric("Best net profit",money(x.best_net_profit_seen));const w=s.wallet||{};$("#walletMetrics").innerHTML=metric("EOA",w.eoa_address||"Not configured")+metric("Proxy",w.proxy_address||"Not configured")+metric("Collateral",w.collateral||"pUSD")+metric("Balance",money(w.usdc_balance))+metric("Exchange allowance",money(w.exchange_allowance))+metric("CTF allowance",money(w.ctf_allowance))+metric("Auth",w.authenticated?"OK":"BLOCKED",stateClass(w.authenticated))+metric("Last refresh",w.last_refresh?new Date(w.last_refresh*1000).toLocaleTimeString():"—");$("#controlState").innerHTML=metric("Armed",s.armed?"YES":"NO",s.armed?"warning-text":"ok")+metric("Kill switch",s.kill_switch?"ACTIVE":"OFF",s.kill_switch?"blocked-text":"ok")+metric("Exposure",money(s.current_exposure))+metric("Incomplete",money(s.incomplete_exposure))+metric("Daily P&L",money(s.risk.daily_pnl))+metric("Circuit breaker",s.risk.is_paused?"PAUSED":"READY",stateClass(!s.risk.is_paused));$("#closest").innerHTML=table(x.closest_opportunities,[["Market",r=>r.market_id],["Signal",r=>r.signal],["Net edge",r=>pct(r.net_edge)],["Net profit",r=>money(r.net_profit)]]);}
async function loadConfig(){const c=await api("/api/config");configValues=c.values;$("#configForm").innerHTML=Object.entries(c.values).map(([k,v])=>`<div class=config-item><label for="cfg-${k}">${k.replaceAll("_"," ")}</label><small>${c.descriptions[k]||"Operational parameter."}</small><input id="cfg-${k}" data-key="${k}" type=number step=any value="${v}"></div>`).join("")}
async function saveConfig(){const values={};document.querySelectorAll("[data-key]").forEach(i=>values[i.dataset.key]=i.dataset.key.includes("_ms")||["max_open_trades","market_limit","circuit_breaker_failure_threshold","circuit_breaker_cooldown_minutes"].includes(i.dataset.key)?Number.parseInt(i.value):Number(i.value));const r=await api("/api/config",{method:"PUT",body:JSON.stringify(values)});$("#configMessage").textContent=r.restart_required?"Saved; restart required.":"Saved and applied without restart.";await loadStatus()}
async function runReadiness(){$("#readinessSummary").innerHTML="<p class=muted>Running read-only checks…</p>";const r=await api("/api/readiness?refresh=true");$("#readinessSummary").innerHTML=`<p class="${r.ready?"ok":"blocked-text"}">${r.ready?"READY TO ARM":"NOT READY — LIVE BLOCKED"}</p>`;$("#readinessChecks").innerHTML=Object.entries(r.checks).map(([k,v])=>`<div class=check><b>${k.replaceAll("_"," ")}</b><span class="${v.status==="ok"?"ok":v.status==="warning"?"warning-text":"blocked-text"}">${v.status.toUpperCase()}</span></div>`).join("")}
async function loadHistory(){const h=await api("/api/history");$("#opportunities").innerHTML=table(h.opportunities,[["Time",r=>new Date(r.timestamp).toLocaleTimeString()],["Market",r=>r.market_id],["Signal",r=>r.signal_type],["Net edge",r=>pct(r.net_edge)],["Profit",r=>money(r.net_profit)],["Decision",r=>r.decision]]);const trades=[...(h.executions||[]),...(h.paper_trades||[])].sort((a,b)=>(b.created_at||b.timestamp)-(a.created_at||a.timestamp));$("#trades").innerHTML=table(trades,[["Mode",r=>r.mode||"paper"],["Market",r=>r.market_id],["State",r=>r.state||(r.success?"COMPLETED":"FAILED")],["P&L",r=>money(r.realized_pnl)],["Latency",r=>`${r.latency_ms||0}ms`]]);$("#riskEvents").innerHTML=table(h.risk_events,[["Time",r=>new Date(r.timestamp).toLocaleTimeString()],["Severity",r=>r.severity],["Event",r=>r.event_type],["Message",r=>r.message]]);$("#systemEvents").innerHTML=table(h.system_events,[["Time",r=>new Date(r.timestamp).toLocaleString()],["Component",r=>r.component],["Event",r=>r.event_type],["Message",r=>r.message]]);}
function toast(msg,bad=false){const t=$("#toast");t.textContent=msg;t.classList.remove("hidden");t.classList.toggle("blocked-text",bad);setTimeout(()=>t.classList.add("hidden"),5000)}
$("#saveConfig").onclick=()=>saveConfig().catch(e=>toast(e.message,true));$("#runReadiness").onclick=()=>runReadiness().catch(e=>toast(e.message,true));$("#refreshWallet").onclick=()=>api("/api/wallet/refresh",{method:"POST"}).then(loadStatus).catch(e=>toast(e.message,true));$("#kill").onclick=()=>api("/api/control/kill",{method:"POST"}).then(loadStatus).catch(e=>toast(e.message,true));$("#resume").onclick=()=>api("/api/control/resume",{method:"POST"}).then(loadStatus).catch(e=>toast(e.message,true));$("#arm").onclick=()=>$("#armDialog").showModal();$("#confirmArm").onclick=e=>{e.preventDefault();api("/api/control/arm",{method:"POST",body:JSON.stringify({confirmation:$("#armConfirmation").value})}).then(()=>{$("#armDialog").close();toast("Live trading armed");loadStatus()}).catch(err=>toast(err.message,true))};
Promise.all([loadStatus(),loadConfig(),loadHistory()]).catch(e=>toast(e.message,true));setInterval(()=>{loadStatus();loadHistory()},5000);
