"""
Data models for Polymarket trading.

Pydantic models for type-safe data handling.
"""

from dataclasses import dataclass, field
from decimal import Decimal
from enum import StrEnum

from pydantic import BaseModel, Field


class OrderSide(StrEnum):
    """Order side (buy or sell)."""

    BUY = "BUY"
    SELL = "SELL"


class OrderType(StrEnum):
    """Order execution type."""

    GTC = "GTC"  # Good Till Cancelled
    FOK = "FOK"  # Fill Or Kill
    GTD = "GTD"  # Good Till Date


class MarketType(StrEnum):
    """Market structure type."""

    BINARY = "binary"          # Standard Yes/No market
    NEG_RISK = "neg_risk"      # Negative risk multi-outcome


@dataclass
class OrderBookLevel:
    """Single level in an order book."""

    price: Decimal
    size: Decimal

    @classmethod
    def from_dict(cls, data: dict) -> "OrderBookLevel":
        """Create from API response dict."""
        return cls(
            price=Decimal(str(data.get("price", "0"))),
            size=Decimal(str(data.get("size", "0"))),
        )


@dataclass
class OrderBook:
    """Order book for a single token."""

    token_id: str
    bids: list[OrderBookLevel] = field(default_factory=list)
    asks: list[OrderBookLevel] = field(default_factory=list)
    timestamp: int | None = None

    @property
    def best_bid(self) -> OrderBookLevel | None:
        """Get the best (highest) bid."""
        return self.bids[0] if self.bids else None

    @property
    def best_ask(self) -> OrderBookLevel | None:
        """Get the best (lowest) ask."""
        return self.asks[0] if self.asks else None

    @property
    def mid_price(self) -> Decimal | None:
        """Calculate mid price between best bid and ask."""
        if self.best_bid and self.best_ask:
            return (self.best_bid.price + self.best_ask.price) / 2
        return None

    @property
    def spread(self) -> Decimal | None:
        """Calculate spread between best ask and bid."""
        if self.best_bid and self.best_ask:
            return self.best_ask.price - self.best_bid.price
        return None


@dataclass
class MarketOutcome:
    """Single outcome in a market."""

    token_id: str
    outcome: str  # "Yes" or "No" for binary, or outcome name for multi
    price: Decimal | None = None
    order_book: OrderBook | None = None


@dataclass
class Market:
    """Polymarket prediction market."""

    condition_id: str
    question: str
    outcomes: list[MarketOutcome]
    market_type: MarketType = MarketType.BINARY
    end_date: str | None = None
    active: bool = True

    @property
    def token_ids(self) -> list[str]:
        """Get all token IDs for this market."""
        return [o.token_id for o in self.outcomes]

    @property
    def is_binary(self) -> bool:
        """Check if this is a binary (Yes/No) market."""
        return len(self.outcomes) == 2


class TradingSignal(BaseModel):
    """Signal generated by arbitrage detection."""

    market_id: str = Field(..., description="Market condition ID")
    signal_type: str = Field(..., description="BUY_SET or SELL_SET")
    token_ids: list[str] = Field(..., description="Token IDs to trade")
    prices: list[str] = Field(..., description="Limit prices for each token")
    size: str = Field(..., description="Trade size (same for all legs)")
    expected_profit: str = Field(..., description="Expected profit in USDC")
    total_cost: str = Field(..., description="Total cost/revenue")
    timestamp: int = Field(..., description="Signal generation timestamp")

    class Config:
        frozen = True


@dataclass
class TradeResult:
    """Result of an executed trade."""

    success: bool
    order_ids: list[str] = field(default_factory=list)
    filled_sizes: list[Decimal] = field(default_factory=list)
    error: str | None = None
    timestamp: int | None = None


@dataclass
class Position:
    """Current position in a market."""

    token_id: str
    size: Decimal
    avg_price: Decimal
    market_id: str | None = None
    outcome: str | None = None

    @property
    def value(self) -> Decimal:
        """Calculate position value at avg price."""
        return self.size * self.avg_price
